repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --check bca_survival tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

    -   id: isort
        name: isort
        entry: isort --check-only bca_survival tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

    -   id: flake8
        name: flake8
        entry: flake8 --max-line-length=120 bca_survival tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

    -   id: mypy
        name: mypy
        entry: mypy bca_survival
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

    -   id: pytest-check
        name: pytest-check
        entry: python -m pytest --cov=bca_survival
        language: system
        pass_filenames: false
        always_run: true